# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "usb_storage" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/47a368f1-90a6-47d7-bb46-ce87e503effc";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D88F-1230";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/70706b4d-26b8-46c5-b000-042966e89b0e"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
